name:                haskell-gloss-helloworld
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- text
- containers
- nonempty-containers
- async
- mtl
- optparse-applicative
- optparse-generic
- aeson
- generic-aeson
- gloss

default-extensions:
- OverloadedStrings

ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wunused-packages

library:
  source-dirs: src

executables:
  haskell-gloss-helloworld-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-gloss-helloworld

tests:
  haskell-gloss-helloworld-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-gloss-helloworld
    - hspec
    - hspec-discover
    - QuickCheck
    - neat-interpolation

verbatim:
  cabal-version: 3.0
